spring:
  application:
    name: business-system
  datasource:
    url: jdbc:mysql://192.168.10.155:3356/db2
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
dubbo:
  application:
    name: business-system
    version: 1.0.0.0
  protocol:
    port: -1
    name: dubbo
  consumer:
    timeout: 3000
  registry:
    address: nacos://192.168.10.155:8848