datasource:
  master:
    url: jdbc:mysql://192.168.3.3:3306/geektime
    username: root
    password: 123456
  slaves:
    - url: jdbc:mysql://127。0。0。1:3306/week_time
      username: root
      password: 123456